"""
Report builder.

Produces two artifacts from a list of summarized items:
  1. HTML string -- used as the email body.
  2. PDF file at a given path -- used as the email attachment.

The HTML is hand-written (not Jinja) to keep dependencies minimal and to
guarantee compatibility with Gmail/Outlook (inline CSS only, no external
stylesheets, no <style> tags relying on cascade).

The PDF uses ReportLab's Platypus (high-level flowables) for clean typography.
"""

from __future__ import annotations

import html
import logging
from collections import defaultdict
from datetime import date, datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)

logger = logging.getLogger(__name__)


# ---------- Helpers ----------

def _stars(rating: int) -> str:
    rating = max(1, min(5, int(rating)))
    return "★" * rating + "☆" * (5 - rating)


def _format_authors(authors: list[str], limit: int = 4) -> str:
    if not authors:
        return ""
    if len(authors) <= limit:
        return ", ".join(authors)
    return ", ".join(authors[:limit]) + f", et al."


def _group_by_topic(items: list[dict]) -> dict[str, list[dict]]:
    """Group items by their first matched topic; preserves importance ordering within group."""
    grouped: dict[str, list[dict]] = defaultdict(list)
    for it in items:
        topics = it.get("matched_topics") or ["Other"]
        grouped[topics[0]].append(it)
    return dict(grouped)


# ---------- HTML email body ----------

# Inline CSS only -- email clients strip <style> tags or block external CSS.
def build_html(items: list[dict], week_label: str) -> str:
    if not items:
        return _empty_html(week_label)

    grouped = _group_by_topic(items)

    parts: list[str] = []
    parts.append(f"""\
<!DOCTYPE html>
<html><body style="font-family: -apple-system, Segoe UI, Helvetica, Arial, sans-serif;
                    color: #222; max-width: 760px; margin: 0 auto; padding: 16px;">
<h1 style="color: #1a3a6c; border-bottom: 2px solid #1a3a6c; padding-bottom: 6px;">
  6G Weekly Survey &mdash; {html.escape(week_label)}
</h1>
<p style="color: #555;">
  {len(items)} item{'s' if len(items) != 1 else ''} across {len(grouped)} topic{'s' if len(grouped) != 1 else ''},
  ranked by importance. PDF attached for offline reading.
</p>
""")

    for topic, group in grouped.items():
        parts.append(f'<h2 style="color:#1a3a6c; margin-top:28px;">{html.escape(topic)}</h2>')
        for it in group:
            llm = it.get("llm", {})
            authors = _format_authors(it.get("authors", []))
            published = it.get("published")
            pub_str = published.strftime("%Y-%m-%d") if isinstance(published, datetime) else ""
            rating = llm.get("importance_1_to_5", 3)

            parts.append(f"""\
<div style="border-left: 4px solid #1a3a6c; padding: 10px 14px; margin: 14px 0;
            background: #f7f9fc; border-radius: 4px;">
  <div style="font-size: 16px; font-weight: 600;">
    <a href="{html.escape(it.get('link', ''))}" style="color:#1a3a6c; text-decoration:none;">
      {html.escape(it.get('title', '(untitled)'))}
    </a>
  </div>
  <div style="color:#666; font-size: 13px; margin: 4px 0 8px 0;">
    {html.escape(authors)}{(' &middot; ' + html.escape(it.get('venue',''))) if it.get('venue') else ''}
    {(' &middot; ' + pub_str) if pub_str else ''}
  </div>
  <div style="margin: 6px 0; font-size: 14px;">
    <span style="color:#d97706; font-size: 16px;">{_stars(rating)}</span>
    <span style="color:#666; margin-left: 6px;">{html.escape(llm.get('importance_rationale', ''))}</span>
  </div>
  <div style="margin: 8px 0; font-size: 14px;">{html.escape(llm.get('summary', ''))}</div>
  <div style="margin: 6px 0; font-size: 14px;">
    <b>Contribution:</b> {html.escape(llm.get('key_contribution', ''))}
  </div>
  <div style="margin: 6px 0; font-size: 14px; color: #1a3a6c;">
    <b>Relevance to your work:</b> {html.escape(llm.get('your_relevance', ''))}
  </div>
</div>
""")

    parts.append("""\
<hr style="margin-top: 28px; border:none; border-top:1px solid #ddd;"/>
<p style="color: #888; font-size: 12px;">
  Generated by 6g-weekly-survey. Tune topics, sources, or recipients in the
  <code>config/</code> folder of the repo.
</p>
</body></html>
""")
    return "".join(parts)


def _empty_html(week_label: str) -> str:
    return f"""\
<!DOCTYPE html>
<html><body style="font-family: Helvetica, Arial, sans-serif; padding: 16px;">
<h1>6G Weekly Survey &mdash; {html.escape(week_label)}</h1>
<p>No relevant items found this week. Consider widening keywords in <code>topics.yaml</code>
   or increasing <code>lookback_days</code> in <code>sources.yaml</code>.</p>
</body></html>
"""


# ---------- PDF builder ----------

def _pdf_styles():
    base = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle("title", parent=base["Title"], textColor=colors.HexColor("#1a3a6c"),
                                fontSize=20, spaceAfter=10),
        "meta": ParagraphStyle("meta", parent=base["Normal"], textColor=colors.grey,
                               fontSize=10, spaceAfter=14),
        "topic_h": ParagraphStyle("topic_h", parent=base["Heading2"], textColor=colors.HexColor("#1a3a6c"),
                                  fontSize=14, spaceBefore=14, spaceAfter=8),
        "paper_title": ParagraphStyle("paper_title", parent=base["Heading3"],
                                      fontSize=12, spaceAfter=2, alignment=TA_LEFT),
        "byline": ParagraphStyle("byline", parent=base["Normal"], textColor=colors.HexColor("#666666"),
                                 fontSize=9, spaceAfter=4),
        "stars": ParagraphStyle("stars", parent=base["Normal"], textColor=colors.HexColor("#d97706"),
                                fontSize=11, spaceAfter=2),
        "body": ParagraphStyle("body", parent=base["Normal"], fontSize=10, spaceAfter=4, leading=13),
        "relevance": ParagraphStyle("relevance", parent=base["Normal"], fontSize=10,
                                    textColor=colors.HexColor("#1a3a6c"), spaceAfter=8, leading=13),
        "footer": ParagraphStyle("footer", parent=base["Normal"], textColor=colors.grey,
                                 fontSize=8, spaceBefore=20),
    }
    return styles


def build_pdf(items: list[dict], week_label: str, out_path: str | Path) -> Path:
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        str(out_path),
        pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=18 * mm, bottomMargin=18 * mm,
        title=f"6G Weekly Survey {week_label}",
        author="6g-weekly-survey",
    )
    s = _pdf_styles()
    story: list = []

    story.append(Paragraph(f"6G Weekly Survey &mdash; {html.escape(week_label)}", s["title"]))

    if not items:
        story.append(Paragraph("No relevant items found this week.", s["body"]))
        doc.build(story)
        return out_path

    grouped = _group_by_topic(items)
    story.append(Paragraph(
        f"{len(items)} items across {len(grouped)} topics, ranked by importance.",
        s["meta"],
    ))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#1a3a6c"), thickness=1.5))

    for topic, group in grouped.items():
        story.append(Paragraph(html.escape(topic), s["topic_h"]))
        for it in group:
            llm = it.get("llm", {})
            authors = _format_authors(it.get("authors", []))
            published = it.get("published")
            pub_str = published.strftime("%Y-%m-%d") if isinstance(published, datetime) else ""

            link = html.escape(it.get("link", ""))
            title_text = html.escape(it.get("title", "(untitled)"))
            story.append(Paragraph(
                f'<link href="{link}" color="#1a3a6c"><b>{title_text}</b></link>',
                s["paper_title"],
            ))

            byline_bits = [b for b in [authors, it.get("venue", ""), pub_str] if b]
            if byline_bits:
                story.append(Paragraph(html.escape(" · ".join(byline_bits)), s["byline"]))

            rating = llm.get("importance_1_to_5", 3)
            story.append(Paragraph(
                f"{_stars(rating)} &nbsp;<font color='#666666' size='9'>"
                f"{html.escape(llm.get('importance_rationale', ''))}</font>",
                s["stars"],
            ))

            story.append(Paragraph(html.escape(llm.get("summary", "")), s["body"]))
            story.append(Paragraph(
                f"<b>Contribution:</b> {html.escape(llm.get('key_contribution', ''))}",
                s["body"],
            ))
            story.append(Paragraph(
                f"<b>Relevance to your work:</b> {html.escape(llm.get('your_relevance', ''))}",
                s["relevance"],
            ))
            story.append(Spacer(1, 6))

    story.append(Spacer(1, 12))
    story.append(Paragraph(
        f"Generated {date.today().isoformat()} by 6g-weekly-survey.",
        s["footer"],
    ))

    doc.build(story)
    logger.info("PDF written to %s", out_path)
    return out_path


# ---------- Smoke test ----------

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    from datetime import timezone
    sample = [
        {
            "id": "arxiv:2401.00001",
            "title": "Neural Receivers for AI-Native 6G",
            "authors": ["A. Researcher", "B. Coauthor", "C. Third", "D. Fourth", "E. Fifth"],
            "venue": "arXiv eess.SP",
            "link": "https://arxiv.org/abs/2401.00001",
            "published": datetime(2026, 5, 15, tzinfo=timezone.utc),
            "matched_topics": ["AI-native air interface"],
            "llm": {
                "summary": "Proposes a Transformer-based receiver for joint channel estimation "
                           "and detection. Trained end-to-end on realistic ray-traced channels. "
                           "Achieves 1.2 dB SNR gain at 1% BLER versus a classical baseline.",
                "key_contribution": "First end-to-end Transformer receiver shown to beat LMMSE+SD on UMa channels.",
                "importance_1_to_5": 5,
                "importance_rationale": "Strong result from a credible group; methodology generalizes.",
                "your_relevance": "Directly relevant to your AI-native air interface program; "
                                  "consider adapting their training pipeline to your CSI compression work.",
            },
        },
        {
            "id": "arxiv:2401.00002",
            "title": "GAN-based Channel Modeling for Sub-THz NTN Links",
            "authors": ["X. Author"],
            "venue": "arXiv cs.IT",
            "link": "https://arxiv.org/abs/2401.00002",
            "published": datetime(2026, 5, 14, tzinfo=timezone.utc),
            "matched_topics": ["Channel modeling / GAN-based"],
            "llm": {
                "summary": "Generative channel model for sub-THz NTN links. Conditional GAN "
                           "captures elevation- and weather-dependent shadowing. Validates "
                           "against measured ITU-R P.681 traces.",
                "key_contribution": "Conditional GAN with explicit elevation conditioning for NTN.",
                "importance_1_to_5": 4,
                "importance_rationale": "Useful methodology, smaller-scale validation.",
                "your_relevance": "Aligns with your GAN-based channel modeling work; "
                                  "the conditioning trick may simplify your LWCM v1 pipeline.",
            },
        },
    ]
    html_body = build_html(sample, "Week of 2026-05-12 to 2026-05-18")
    Path("/tmp/test_report.html").write_text(html_body)
    pdf_path = build_pdf(sample, "Week of 2026-05-12 to 2026-05-18", "/tmp/test_report.pdf")
    print(f"HTML: /tmp/test_report.html ({len(html_body)} bytes)")
    print(f"PDF:  {pdf_path} ({pdf_path.stat().st_size} bytes)")
